name: Build ScpReroll

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: ScpReroll
          path: bin/Release/net48/ScpReroll.dll
